default_platform(:ios)

desc "Building your App in beta version"
lane :beta do |options|       # invokes cert
    build(profile: options[:env])
    firebase_app_distribution(
      app: ENV['APP_ID'],
      groups: ENV["GROUPS"] || options[:groups],
      release_notes: options[:notes] || "",
    )
end

private_lane :build do |options|
    puts "+------------------------------------+".bold.blue
    puts "|-- Environment: #{options[:profile]} 🚀 --|".bold.blue
    puts "+------------------------------------+".bold.blue

    increment_build_number()

    scheme = ENV['SCHEME_NAME']
    method = "ad-hoc"
    profile = ENV['DISTRIBUTION_PROFILE_FIREBASE']
    build_app(
      scheme: scheme,
      export_options: {
        method: method,
        provisioningProfiles: {
          ENV['BUNDLE_ID'] => profile
        }
      },
      include_bitcode: true,
      clean: true,
    )
end