name: Distribute

on:
  push:
    branches: [ 'feature/bug-fixes' ]

jobs:
  distribute:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      
      - name: Install bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      
      - name: Distribute app with 🔥 App Distribution 🚀
        run: bundle exec fastlane beta