name: Distribute to firebase

on:
  push:
    branches:
      - main

jobs:
  distribute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: setup fastlane
        run: bundle install && gem install fastlane
      - name: distribute to firebase
        working-directory: ./android
        run: npm install && sudo fastlane beta
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          GROUPS: ${{ secrets.GROUPS }}